"""Пример регистрации виджетов для типов данных.

Что происходит:

Через WidgetFactory.register_widget задаётся:
StrictStr → StringWidget
StrictInt → IntegerWidget
После этого все такие типы автоматически используют нужные виджеты

Что полезного показывает:

Глобальную настройку: тип → виджет
Как адаптировать библиотеку под свой стек (например OpenAPI DTO)"""

from typing import Optional

from nicegui import APIRouter, ui
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr

from ._layout import base, TheNavigation
from niceforms import BaseModelForm
from niceforms.widget.integer import IntegerWidget
from niceforms.widget.string import StringWidget
from niceforms.widget_factory import WidgetFactory

router = APIRouter()


class CreateUserDTO(BaseModel):
    """
    Generated CreateUserDTO from openapi-generator-cli
    Generated by OpenAPI Generator (https://openapi-generator.tech)
    """

    email: StrictStr = Field(description="Email пользователя")
    username: Optional[StrictStr]
    first_name: Optional[StrictStr]
    middle_name: Optional[StrictStr]
    last_name: Optional[StrictStr]
    active: StrictBool
    company_id: StrictInt


WidgetFactory.register_widget(field_type=StrictStr, widget=StringWidget)
WidgetFactory.register_widget(field_type=StrictInt, widget=IntegerWidget)


@router.page('/custom_type_widget')
@base
async def basic() -> None:
    WidgetFactory.print_widget_registry()

    with ui.column().classes('w-full max-w-2xl mx-auto'):
        TheNavigation(
            description='Когда у тебя много моделей и не хочется настраивать каждое поле вручную'
        ).render()

        async def submit_handler(model: CreateUserDTO) -> None:
            print(f"Пользователь создан: {model}")

        form = BaseModelForm(
            CreateUserDTO, on_submit=submit_handler, view_annotation_type=False
        )
        form.render()
